version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloudpwd
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - nextcloud-net
    expose:
      - "3306"

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8082:80"
    environment:
      MYSQL_PASSWORD: nextcloudpwd
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: mariadb
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - nextcloud-net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8085:8080"
    networks:
      - nextcloud-net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - nextcloud-net

volumes:
  mariadb_data:
  nextcloud_data:
  portainer_data:

networks:
  nextcloud-net:
